version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_moodiary
    restart: unless-stopped
    environment:
      POSTGRES_DB: moodiary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_contrasena
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - moodiary-net

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: moodiary_backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - moodiary-net
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: moodiary_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - moodiary-net
    environment:
      - VITE_BACKEND_URL=http://localhost:5001
    # ❌ No pongas volumes aquí si estás haciendo producción con build + serve

# 👇 ESTO VA FUERA DE services:
volumes:
  postgres_data:

networks:
  moodiary-net:
    driver: bridge
